#los datos los toma R como tipo factor sin embargo para asignarles valores num'ericos que
#es como se desea trabajar, se pasan a tipo caracter primero luego se convertir'an a tipo numerico
cambia_tipo_fc=function(dataSet){
  
  #DD
  
  
  # ifelse(is.na(dataSet$DD1),dataSet$DD1<-NA,dataSet$DD1<-as.character(dataSet$DD1))
  # ifelse(is.na(dataSet$DD2),dataSet$DD2<-NA,dataSet$DD2<-as.character(dataSet$DD2)) 
  # ifelse(is.na(dataSet$DD3),dataSet$DD3<-NA,dataSet$DD3<-as.character(dataSet$DD3)) 
  # ifelse(is.na(dataSet$DD4),dataSet$DD4<-NA,dataSet$DD4<-as.character(dataSet$DD4)) 
  # ifelse(is.na(dataSet$DD5),dataSet$DD5<-NA,dataSet$DD5<-as.character(dataSet$DD5))
  # ifelse(is.na(dataSet$DD6),dataSet$DD6<-NA,dataSet$DD6<-as.character(dataSet$DD6))
  # ifelse(is.na(dataSet$DD7),dataSet$DD7<-NA,dataSet$DD7<-as.character(dataSet$DD7))
  # ifelse(is.na(dataSet$DD8),dataSet$DD8<-NA,dataSet$DD8<-as.character(dataSet$DD8))
  
  
  dataSet$DD1<-as.character(dataSet$DD1)
  dataSet$DD2<-as.character(dataSet$DD2)
  dataSet$DD3<-as.character(dataSet$DD3)
  dataSet$DD4<-as.character(dataSet$DD4)
  dataSet$DD5<-as.character(dataSet$DD5)
  dataSet$DD6<-as.character(dataSet$DD6)
  dataSet$DD7<-as.character(dataSet$DD7)
  dataSet$DD8<-as.character(dataSet$DD8)
  
  
  #PSQI
  # ifelse(is.na(dataSet$SQ6),dataSet$SQ6<-NA,dataSet$SQ6<-as.character(dataSet$SQ1))
  # ifelse(is.na(dataSet$SQ7),dataSet$SQ7<-NA,dataSet$SQ7<-as.character(dataSet$SQ2))
  # ifelse(is.na(dataSet$SQ8),dataSet$SQ8<-NA,dataSet$SQ8<-as.character(dataSet$SQ3))
  # ifelse(is.na(dataSet$SQ9),dataSet$SQ9<-NA,dataSet$SQ9<-as.character(dataSet$SQ4))
  # ifelse(is.na(dataSet$SQ5a),dataSet$SQ5a<-NA,dataSet$SQ5a<-as.character(dataSet$SQ5a))
  # ifelse(is.na(dataSet$SQ5b),dataSet$SQ5b<-NA,dataSet$SQ5b<-as.character(dataSet$SQ5b))
  # ifelse(is.na(dataSet$SQ5c),dataSet$SQ5c<-NA,dataSet$SQ5c<-as.character(dataSet$SQ5c))
  # ifelse(is.na(dataSet$SQ5d),dataSet$SQ5d<-NA,dataSet$SQ5d<-as.character(dataSet$SQ5d))
  # ifelse(is.na(dataSet$SQ5e),dataSet$SQ5e<-NA,dataSet$SQ5e<-as.character(dataSet$SQ5e))
  # ifelse(is.na(dataSet$SQ5f),dataSet$SQ5f<-NA,dataSet$SQ5f<-as.character(dataSet$SQ5f))
  # ifelse(is.na(dataSet$SQ5g),dataSet$SQ5g<-NA,dataSet$SQ5g<-as.character(dataSet$SQ5g))
  # ifelse(is.na(dataSet$SQ5h),dataSet$SQ5h<-NA,dataSet$SQ5h<-as.character(dataSet$SQ5h))
  # ifelse(is.na(dataSet$SQ5i),dataSet$SQ5i<-NA,dataSet$SQ5i<-as.character(dataSet$SQ5i))
  # ifelse(is.na(dataSet$SQ5j),dataSet$SQ5j<-NA,dataSet$SQ5j<-as.character(dataSet$SQ5j))
  # ifelse(is.na(dataSet$SQ6),dataSet$SQ6<-NA,dataSet$SQ6<-as.character(dataSet$SQ6))
  # ifelse(is.na(dataSet$SQ7),dataSet$SQ7<-NA,dataSet$SQ7<-as.character(dataSet$SQ7))
  # ifelse(is.na(dataSet$SQ8),dataSet$SQ8<-NA,dataSet$SQ8<-as.character(dataSet$SQ8))
  # ifelse(is.na(dataSet$SQ9),dataSet$SQ9<-NA,dataSet$SQ9<-as.character(dataSet$SQ9))
  
  
  dataSet$SQ1<-as.character(dataSet$SQ1)
  dataSet$SQ2<-as.character(dataSet$SQ2)
  dataSet$SQ3<-as.character(dataSet$SQ3)
  dataSet$SQ4<-as.character(dataSet$SQ4)
  dataSet$SQ5a<-as.character(dataSet$SQ5a)
  dataSet$SQ5b<-as.character(dataSet$SQ5b)
  dataSet$SQ5c<-as.character(dataSet$SQ5c)
  dataSet$SQ5d<-as.character(dataSet$SQ5d)
  dataSet$SQ5e<-as.character(dataSet$SQ5e)
  dataSet$SQ5f<-as.character(dataSet$SQ5f)
  dataSet$SQ5g<-as.character(dataSet$SQ5g)
  dataSet$SQ5h<-as.character(dataSet$SQ5h)
  dataSet$SQ5i<-as.character(dataSet$SQ5i)
  dataSet$SQ5j<-as.character(dataSet$SQ5j)
  dataSet$SQ6<-as.character(dataSet$SQ6)
  dataSet$SQ7<-as.character(dataSet$SQ7)
  dataSet$SQ8<-as.character(dataSet$SQ8)
  dataSet$SQ9<-as.character(dataSet$SQ9)
  
  #SHI
  # ifelse(is.na(dataSet$SH1),dataSet$SH1<-NA,dataSet$SH1<-as.character(dataSet$SH1))
  # ifelse(is.na(dataSet$SH2),dataSet$SH2<-NA,dataSet$SH2<-as.character(dataSet$SH2))
  # ifelse(is.na(dataSet$SH3),dataSet$SH3<-NA,dataSet$SH3<-as.character(dataSet$SH3))
  # ifelse(is.na(dataSet$SH4),dataSet$SH4<-NA,dataSet$SH4<-as.character(dataSet$SH4))
  # ifelse(is.na(dataSet$SH5),dataSet$SH5<-NA,dataSet$SH5<-as.character(dataSet$SH5))
  # ifelse(is.na(dataSet$SH6),dataSet$SH6<-NA,dataSet$SH6<-as.character(dataSet$SH6))
  # ifelse(is.na(dataSet$SH7),dataSet$SH7<-NA,dataSet$SH7<-as.character(dataSet$SH7))
  # ifelse(is.na(dataSet$SH8),dataSet$SH8<-NA,dataSet$SH8<-as.character(dataSet$SH8))
  # ifelse(is.na(dataSet$SH9),dataSet$SH9<-NA,dataSet$SH9<-as.character(dataSet$SH9))
  # ifelse(is.na(dataSet$SH10),dataSet$SH10<-NA,dataSet$SH10<-as.character(dataSet$SH10))
  # ifelse(is.na(dataSet$SH11),dataSet$SH11<-NA,dataSet$SH11<-as.character(dataSet$SH11))
  # ifelse(is.na(dataSet$SH12),dataSet$SH12<-NA,dataSet$SH12<-as.character(dataSet$SH12))
  # ifelse(is.na(dataSet$SH13),dataSet$SH13<-NA,dataSet$SH13<-as.character(dataSet$SH13))
  # ifelse(is.na(dataSet$SH14),dataSet$SH14<-NA,dataSet$SH14<-as.character(dataSet$SH14))
  # ifelse(is.na(dataSet$SH15),dataSet$SH15<-NA,dataSet$SH15<-as.character(dataSet$SH15))
  # ifelse(is.na(dataSet$SH16),dataSet$SH16<-NA,dataSet$SH16<-as.character(dataSet$SH16))
  # ifelse(is.na(dataSet$SH17),dataSet$SH17<-NA,dataSet$SH17<-as.character(dataSet$SH17))
  # ifelse(is.na(dataSet$SH18),dataSet$SH18<-NA,dataSet$SH18<-as.character(dataSet$SH18))
  # ifelse(is.na(dataSet$SH19),dataSet$SH19<-NA,dataSet$SH19<-as.character(dataSet$SH19))
  # ifelse(is.na(dataSet$SH20),dataSet$SH20<-NA,dataSet$SH20<-as.character(dataSet$SH20))
  # ifelse(is.na(dataSet$SH21),dataSet$SH21<-NA,dataSet$SH21<-as.character(dataSet$SH21))
  
  dataSet$SH1<-as.character(dataSet$SH1)
  dataSet$SH2<-as.character(dataSet$SH2)
  dataSet$SH3<-as.character(dataSet$SH3)
  dataSet$SH4<-as.character(dataSet$SH4)
  dataSet$SH5<-as.character(dataSet$SH5)
  dataSet$SH6<-as.character(dataSet$SH6)
  dataSet$SH7<-as.character(dataSet$SH7)
  dataSet$SH8<-as.character(dataSet$SH8)
  dataSet$SH9<-as.character(dataSet$SH9)
  dataSet$SH10<-as.character(dataSet$SH10)
  dataSet$SH11<-as.character(dataSet$SH11)
  dataSet$SH12<-as.character(dataSet$SH12)
  dataSet$SH13<-as.character(dataSet$SH13)
  dataSet$SH14<-as.character(dataSet$SH14)
  dataSet$SH15<-as.character(dataSet$SH15)
  dataSet$SH16<-as.character(dataSet$SH16)
  dataSet$SH17<-as.character(dataSet$SH17)
  dataSet$SH18<-as.character(dataSet$SH18)
  dataSet$SH19<-as.character(dataSet$SH19)
  dataSet$SH20<-as.character(dataSet$SH20)
  dataSet$SH21<-as.character(dataSet$SH21)
  
  
  return(dataSet)
}